class CountryName
{
    static CountryName =
    {
        AF:'Afghanistan',
        AL:'Albania',
        DZ:'Algeria',
        AD:'Andorra',
        AO:'Angola',
        AQ:'Antarctica',
        AR:'Argentina',
        AM:'Armenia',
        AW:'Aruba',
        AU:'Australia',
        AT:'Austria',
        AZ:'Azerbaijan',
        BH:'Bahrain',
        BD:'Bangladesh',
        BY:'Belarus',
        BE:'Belgium',
        BZ:'Belize',
        BJ:'Benin',
        BT:'Bhutan',
        BO:'Bolivia, Plurinational State Of',
        BA:'Bosnia And Herzegovina',
        BW:'Botswana',
        BR:'Brazil',
        BN:'Brunei Darussalam',
        BG:'Bulgaria',
        BF:'Burkina Faso',
        MM:'Myanmar',
        BI:'Burundi',
        KH:'Cambodia',
        CM:'Cameroon',
        CA:'Canada',
        CV:'Cape Verde',
        CF:'Central African Republic',
        TD:'Chad',
        CL:'Chile',
        CN:'China',
        CX:'Christmas Island',
        CC:'Cocos (keeling) Islands',
        CO:'Colombia',
        KM:'Comoros',
        CG:'Congo',
        CD:'Congo, The Democratic Republic Of The',
        CK:'Cook Islands',
        CR:'Costa Rica',
        HR:'Croatia',
        CU:'Cuba',
        CY:'Cyprus',
        CZ:'Czech Republic',
        DK:'Denmark',
        DJ:'Djibouti',
        TL:'Timor-leste',
        EC:'Ecuador',
        EG:'Egypt',
        SV:'El Salvador',
        GQ:'Equatorial Guinea',
        ER:'Eritrea',
        EE:'Estonia',
        ET:'Ethiopia',
        FK:'Falkland Islands (malvinas)',
        FO:'Faroe Islands',
        FJ:'Fiji',
        FI:'Finland',
        FR:'France',
        PF:'French Polynesia',
        GA:'Gabon',
        GM:'Gambia',
        GE:'Georgia',
        DE:'Germany',
        GH:'Ghana',
        GI:'Gibraltar',
        GR:'Greece',
        GL:'Greenland',
        GT:'Guatemala',
        GN:'Guinea',
        GW:'Guinea-bissau',
        GY:'Guyana',
        HT:'Haiti',
        HN:'Honduras',
        HK:'Hong Kong',
        HU:'Hungary',
        IN:'India',
        ID:'Indonesia',
        IR:'Iran, Islamic Republic Of',
        IQ:'Iraq',
        IE:'Ireland',
        IM:'Isle Of Man',
        IL:'Israel',
        IT:'Italy',
        CI:'Côte D&apos,ivoire',
        JP:'Japan',
        JO:'Jordan',
        KZ:'Kazakhstan',
        KE:'Kenya',
        KI:'Kiribati',
        KW:'Kuwait',
        KG:'Kyrgyzstan',
        LA:'Lao People&apos,s Democratic Republic',
        LV:'Latvia',
        LB:'Lebanon',
        LS:'Lesotho',
        LR:'Liberia',
        LY:'Libya',
        LI:'Liechtenstein',
        LT:'Lithuania',
        LU:'Luxembourg',
        MO:'Macao',
        MK:'Macedonia, The Former Yugoslav Republic Of',
        MG:'Madagascar',
        MW:'Malawi',
        MY:'Malaysia',
        MV:'Maldives',
        ML:'Mali',
        MT:'Malta',
        MH:'Marshall Islands',
        MR:'Mauritania',
        MU:'Mauritius',
        YT:'Mayotte',
        MX:'Mexico',
        FM:'Micronesia, Federated States Of',
        MD:'Moldova, Republic Of',
        MC:'Monaco',
        MN:'Mongolia',
        ME:'Montenegro',
        MA:'Morocco',
        MZ:'Mozambique',
        NA:'Namibia',
        NR:'Nauru',
        NP:'Nepal',
        NL:'Netherlands',
        NC:'New Caledonia',
        NZ:'New Zealand',
        NI:'Nicaragua',
        NE:'Niger',
        NG:'Nigeria',
        NU:'Niue',
        KP:'Korea, Democratic People&apos,s Republic Of',
        NO:'Norway',
        OM:'Oman',
        PK:'Pakistan',
        PW:'Palau',
        PA:'Panama',
        PG:'Papua New Guinea',
        PY:'Paraguay',
        PE:'Peru',
        PH:'Philippines',
        PN:'Pitcairn',
        PL:'Poland',
        PT:'Portugal',
        PR:'Puerto Rico',
        QA:'Qatar',
        RO:'Romania',
        RU:'Russian Federation',
        RW:'Rwanda',
        BL:'Saint Barthélemy',
        WS:'Samoa',
        SM:'San Marino',
        ST:'Sao Tome And Principe',
        SA:'Saudi Arabia',
        SN:'Senegal',
        RS:'Serbia',
        SC:'Seychelles',
        SL:'Sierra Leone',
        SG:'Singapore',
        SK:'Slovakia',
        SI:'Slovenia',
        SB:'Solomon Islands',
        SO:'Somalia',
        ZA:'South Africa',
        KR:'Korea, Republic Of',
        ES:'Spain',
        LK:'Sri Lanka',
        SH:'Saint Helena, Ascension And Tristan Da Cunha',
        PM:'Saint Pierre And Miquelon',
        SD:'Sudan',
        SR:'Suriname',
        SZ:'Swaziland',
        SE:'Sweden',
        CH:'Switzerland',
        SY:'Syrian Arab Republic',
        TW:'Taiwan, Province Of China',
        TJ:'Tajikistan',
        TZ:'Tanzania, United Republic Of',
        TH:'Thailand',
        TG:'Togo',
        TK:'Tokelau',
        TO:'Tonga',
        TN:'Tunisia',
        TR:'Turkey',
        TM:'Turkmenistan',
        TV:'Tuvalu',
        AE:'United Arab Emirates',
        UG:'Uganda',
        GB:'United Kingdom',
        UA:'Ukraine',
        UY:'Uruguay',
        US:'United States',
        UZ:'Uzbekistan',
        VU:'Vanuatu',
        VA:'Holy See (vatican City State)',
        VE:'Venezuela, Bolivarian Republic Of',
        VN:'Viet Nam',
        WF:'Wallis And Futuna',
        YE:'Yemen',
        ZM:'Zambia',
        ZW:'Zimbabwe'
    }
}
export = CountryName