class CountryCode
{
    static AF = {code: 'af', phoneCode: '93', name: 'Afghanistan'}
    static AL = {code: 'al', phoneCode: '355', name: 'Albania'}
    static DZ = {code: 'dz', phoneCode: '213', name: 'Algeria'}
    static AD = {code: 'ad', phoneCode: '376', name: 'Andorra'}
    static AO = {code: 'ao', phoneCode: '244', name: 'Angola'}
    static AQ = {code: 'aq', phoneCode: '672', name: 'Antarctica'}
    static AR = {code: 'ar', phoneCode: '54', name: 'Argentina'}
    static AM = {code: 'am', phoneCode: '374', name: 'Armenia'}
    static AW = {code: 'aw', phoneCode: '297', name: 'Aruba'}
    static AU = {code: 'au', phoneCode: '61', name: 'Australia'}
    static AT = {code: 'at', phoneCode: '43', name: 'Austria'}
    static AZ = {code: 'az', phoneCode: '994', name: 'Azerbaijan'}
    static BH = {code: 'bh', phoneCode: '973', name: 'Bahrain'}
    static BD = {code: 'bd', phoneCode: '880', name: 'Bangladesh'}
    static BY = {code: 'by', phoneCode: '375', name: 'Belarus'}
    static BE = {code: 'be', phoneCode: '32', name: 'Belgium'}
    static BZ = {code: 'bz', phoneCode: '501', name: 'Belize'}
    static BJ = {code: 'bj', phoneCode: '229', name: 'Benin'}
    static BT = {code: 'bt', phoneCode: '975', name: 'Bhutan'}
    static BO = {code: 'bo', phoneCode: '591', name: 'Bolivia, Plurinational State Of'}
    static BA = {code: 'ba', phoneCode: '387', name: 'Bosnia And Herzegovina'}
    static BW = {code: 'bw', phoneCode: '267', name: 'Botswana'}
    static BR = {code: 'br', phoneCode: '55', name: 'Brazil'}
    static BN = {code: 'bn', phoneCode: '673', name: 'Brunei Darussalam'}
    static BG = {code: 'bg', phoneCode: '359', name: 'Bulgaria'}
    static BF = {code: 'bf', phoneCode: '226', name: 'Burkina Faso'}
    static MM = {code: 'mm', phoneCode: '95', name: 'Myanmar'}
    static BI = {code: 'bi', phoneCode: '257', name: 'Burundi'}
    static KH = {code: 'kh', phoneCode: '855', name: 'Cambodia'}
    static CM = {code: 'cm', phoneCode: '237', name: 'Cameroon'}
    static CA = {code: 'ca', phoneCode: '1', name: 'Canada'}
    static CV = {code: 'cv', phoneCode: '238', name: 'Cape Verde'}
    static CF = {code: 'cf', phoneCode: '236', name: 'Central African Republic'}
    static TD = {code: 'td', phoneCode: '235', name: 'Chad'}
    static CL = {code: 'cl', phoneCode: '56', name: 'Chile'}
    static CN = {code: 'cn', phoneCode: '86', name: 'China'}
    static CX = {code: 'cx', phoneCode: '61', name: 'Christmas Island'}
    static CC = {code: 'cc', phoneCode: '61', name: 'Cocos (keeling) Islands'}
    static CO = {code: 'co', phoneCode: '57', name: 'Colombia'}
    static KM = {code: 'km', phoneCode: '269', name: 'Comoros'}
    static CG = {code: 'cg', phoneCode: '242', name: 'Congo'}
    static CD = {code: 'cd', phoneCode: '243', name: 'Congo, The Democratic Republic Of The'}
    static CK = {code: 'ck', phoneCode: '682', name: 'Cook Islands'}
    static CR = {code: 'cr', phoneCode: '506', name: 'Costa Rica'}
    static HR = {code: 'hr', phoneCode: '385', name: 'Croatia'}
    static CU = {code: 'cu', phoneCode: '53', name: 'Cuba'}
    static CY = {code: 'cy', phoneCode: '357', name: 'Cyprus'}
    static CZ = {code: 'cz', phoneCode: '420', name: 'Czech Republic'}
    static DK = {code: 'dk', phoneCode: '45', name: 'Denmark'}
    static DJ = {code: 'dj', phoneCode: '253', name: 'Djibouti'}
    static TL = {code: 'tl', phoneCode: '670', name: 'Timor-leste'}
    static EC = {code: 'ec', phoneCode: '593', name: 'Ecuador'}
    static EG = {code: 'eg', phoneCode: '20', name: 'Egypt'}
    static SV = {code: 'sv', phoneCode: '503', name: 'El Salvador'}
    static GQ = {code: 'gq', phoneCode: '240', name: 'Equatorial Guinea'}
    static ER = {code: 'er', phoneCode: '291', name: 'Eritrea'}
    static EE = {code: 'ee', phoneCode: '372', name: 'Estonia'}
    static ET = {code: 'et', phoneCode: '251', name: 'Ethiopia'}
    static FK = {code: 'fk', phoneCode: '500', name: 'Falkland Islands (malvinas)'}
    static FO = {code: 'fo', phoneCode: '298', name: 'Faroe Islands'}
    static FJ = {code: 'fj', phoneCode: '679', name: 'Fiji'}
    static FI = {code: 'fi', phoneCode: '358', name: 'Finland'}
    static FR = {code: 'fr', phoneCode: '33', name: 'France'}
    static PF = {code: 'pf', phoneCode: '689', name: 'French Polynesia'}
    static GA = {code: 'ga', phoneCode: '241', name: 'Gabon'}
    static GM = {code: 'gm', phoneCode: '220', name: 'Gambia'}
    static GE = {code: 'ge', phoneCode: '995', name: 'Georgia'}
    static DE = {code: 'de', phoneCode: '49', name: 'Germany'}
    static GH = {code: 'gh', phoneCode: '233', name: 'Ghana'}
    static GI = {code: 'gi', phoneCode: '350', name: 'Gibraltar'}
    static GR = {code: 'gr', phoneCode: '30', name: 'Greece'}
    static GL = {code: 'gl', phoneCode: '299', name: 'Greenland'}
    static GT = {code: 'gt', phoneCode: '502', name: 'Guatemala'}
    static GN = {code: 'gn', phoneCode: '224', name: 'Guinea'}
    static GW = {code: 'gw', phoneCode: '245', name: 'Guinea-bissau'}
    static GY = {code: 'gy', phoneCode: '592', name: 'Guyana'}
    static HT = {code: 'ht', phoneCode: '509', name: 'Haiti'}
    static HN = {code: 'hn', phoneCode: '504', name: 'Honduras'}
    static HK = {code: 'hk', phoneCode: '852', name: 'Hong Kong'}
    static HU = {code: 'hu', phoneCode: '36', name: 'Hungary'}
    static IN = {code: 'in', phoneCode: '91', name: 'India'}
    static ID = {code: 'id', phoneCode: '62', name: 'Indonesia'}
    static IR = {code: 'ir', phoneCode: '98', name: 'Iran, Islamic Republic Of'}
    static IQ = {code: 'iq', phoneCode: '964', name: 'Iraq'}
    static IE = {code: 'ie', phoneCode: '353', name: 'Ireland'}
    static IM = {code: 'im', phoneCode: '44', name: 'Isle Of Man'}
    static IL = {code: 'il', phoneCode: '972', name: 'Israel'}
    static IT = {code: 'it', phoneCode: '39', name: 'Italy'}
    static CI = {code: 'ci', phoneCode: '225', name: 'Côte D&apos;ivoire'}
    static JP = {code: 'jp', phoneCode: '81', name: 'Japan'}
    static JO = {code: 'jo', phoneCode: '962', name: 'Jordan'}
    static KZ = {code: 'kz', phoneCode: '7', name: 'Kazakhstan'}
    static KE = {code: 'ke', phoneCode: '254', name: 'Kenya'}
    static KI = {code: 'ki', phoneCode: '686', name: 'Kiribati'}
    static KW = {code: 'kw', phoneCode: '965', name: 'Kuwait'}
    static KG = {code: 'kg', phoneCode: '996', name: 'Kyrgyzstan'}
    static LA = {code: 'la', phoneCode: '856', name: 'Lao People&apos;s Democratic Republic'}
    static LV = {code: 'lv', phoneCode: '371', name: 'Latvia'}
    static LB = {code: 'lb', phoneCode: '961', name: 'Lebanon'}
    static LS = {code: 'ls', phoneCode: '266', name: 'Lesotho'}
    static LR = {code: 'lr', phoneCode: '231', name: 'Liberia'}
    static LY = {code: 'ly', phoneCode: '218', name: 'Libya'}
    static LI = {code: 'li', phoneCode: '423', name: 'Liechtenstein'}
    static LT = {code: 'lt', phoneCode: '370', name: 'Lithuania'}
    static LU = {code: 'lu', phoneCode: '352', name: 'Luxembourg'}
    static MO = {code: 'mo', phoneCode: '853', name: 'Macao'}
    static MK = {code: 'mk', phoneCode: '389', name: 'Macedonia, The Former Yugoslav Republic Of'}
    static MG = {code: 'mg', phoneCode: '261', name: 'Madagascar'}
    static MW = {code: 'mw', phoneCode: '265', name: 'Malawi'}
    static MY = {code: 'my', phoneCode: '60', name: 'Malaysia'}
    static MV = {code: 'mv', phoneCode: '960', name: 'Maldives'}
    static ML = {code: 'ml', phoneCode: '223', name: 'Mali'}
    static MT = {code: 'mt', phoneCode: '356', name: 'Malta'}
    static MH = {code: 'mh', phoneCode: '692', name: 'Marshall Islands'}
    static MR = {code: 'mr', phoneCode: '222', name: 'Mauritania'}
    static MU = {code: 'mu', phoneCode: '230', name: 'Mauritius'}
    static YT = {code: 'yt', phoneCode: '262', name: 'Mayotte'}
    static MX = {code: 'mx', phoneCode: '52', name: 'Mexico'}
    static FM = {code: 'fm', phoneCode: '691', name: 'Micronesia, Federated States Of'}
    static MD = {code: 'md', phoneCode: '373', name: 'Moldova, Republic Of'}
    static MC = {code: 'mc', phoneCode: '377', name: 'Monaco'}
    static MN = {code: 'mn', phoneCode: '976', name: 'Mongolia'}
    static ME = {code: 'me', phoneCode: '382', name: 'Montenegro'}
    static MA = {code: 'ma', phoneCode: '212', name: 'Morocco'}
    static MZ = {code: 'mz', phoneCode: '258', name: 'Mozambique'}
    static NA = {code: 'na', phoneCode: '264', name: 'Namibia'}
    static NR = {code: 'nr', phoneCode: '674', name: 'Nauru'}
    static NP = {code: 'np', phoneCode: '977', name: 'Nepal'}
    static NL = {code: 'nl', phoneCode: '31', name: 'Netherlands'}
    static NC = {code: 'nc', phoneCode: '687', name: 'New Caledonia'}
    static NZ = {code: 'nz', phoneCode: '64', name: 'New Zealand'}
    static NI = {code: 'ni', phoneCode: '505', name: 'Nicaragua'}
    static NE = {code: 'ne', phoneCode: '227', name: 'Niger'}
    static NG = {code: 'ng', phoneCode: '234', name: 'Nigeria'}
    static NU = {code: 'nu', phoneCode: '683', name: 'Niue'}
    static KP = {code: 'kp', phoneCode: '850', name: 'Korea, Democratic People&apos;s Republic Of'}
    static NO = {code: 'no', phoneCode: '47', name: 'Norway'}
    static OM = {code: 'om', phoneCode: '968', name: 'Oman'}
    static PK = {code: 'pk', phoneCode: '92', name: 'Pakistan'}
    static PW = {code: 'pw', phoneCode: '680', name: 'Palau'}
    static PA = {code: 'pa', phoneCode: '507', name: 'Panama'}
    static PG = {code: 'pg', phoneCode: '675', name: 'Papua New Guinea'}
    static PY = {code: 'py', phoneCode: '595', name: 'Paraguay'}
    static PE = {code: 'pe', phoneCode: '51', name: 'Peru'}
    static PH = {code: 'ph', phoneCode: '63', name: 'Philippines'}
    static PN = {code: 'pn', phoneCode: '870', name: 'Pitcairn'}
    static PL = {code: 'pl', phoneCode: '48', name: 'Poland'}
    static PT = {code: 'pt', phoneCode: '351', name: 'Portugal'}
    static PR = {code: 'pr', phoneCode: '1', name: 'Puerto Rico'}
    static QA = {code: 'qa', phoneCode: '974', name: 'Qatar'}
    static RO = {code: 'ro', phoneCode: '40', name: 'Romania'}
    static RU = {code: 'ru', phoneCode: '7', name: 'Russian Federation'}
    static RW = {code: 'rw', phoneCode: '250', name: 'Rwanda'}
    static BL = {code: 'bl', phoneCode: '590', name: 'Saint Barthélemy'}
    static WS = {code: 'ws', phoneCode: '685', name: 'Samoa'}
    static SM = {code: 'sm', phoneCode: '378', name: 'San Marino'}
    static ST = {code: 'st', phoneCode: '239', name: 'Sao Tome And Principe'}
    static SA = {code: 'sa', phoneCode: '966', name: 'Saudi Arabia'}
    static SN = {code: 'sn', phoneCode: '221', name: 'Senegal'}
    static RS = {code: 'rs', phoneCode: '381', name: 'Serbia'}
    static SC = {code: 'sc', phoneCode: '248', name: 'Seychelles'}
    static SL = {code: 'sl', phoneCode: '232', name: 'Sierra Leone'}
    static SG = {code: 'sg', phoneCode: '65', name: 'Singapore'}
    static SK = {code: 'sk', phoneCode: '421', name: 'Slovakia'}
    static SI = {code: 'si', phoneCode: '386', name: 'Slovenia'}
    static SB = {code: 'sb', phoneCode: '677', name: 'Solomon Islands'}
    static SO = {code: 'so', phoneCode: '252', name: 'Somalia'}
    static ZA = {code: 'za', phoneCode: '27', name: 'South Africa'}
    static KR = {code: 'kr', phoneCode: '82', name: 'Korea, Republic Of'}
    static ES = {code: 'es', phoneCode: '34', name: 'Spain'}
    static LK = {code: 'lk', phoneCode: '94', name: 'Sri Lanka'}
    static SH = {code: 'sh', phoneCode: '290', name: 'Saint Helena, Ascension And Tristan Da Cunha'}
    static PM = {code: 'pm', phoneCode: '508', name: 'Saint Pierre And Miquelon'}
    static SD = {code: 'sd', phoneCode: '249', name: 'Sudan'}
    static SR = {code: 'sr', phoneCode: '597', name: 'Suriname'}
    static SZ = {code: 'sz', phoneCode: '268', name: 'Swaziland'}
    static SE = {code: 'se', phoneCode: '46', name: 'Sweden'}
    static CH = {code: 'ch', phoneCode: '41', name: 'Switzerland'}
    static SY = {code: 'sy', phoneCode: '963', name: 'Syrian Arab Republic'}
    static TW = {code: 'tw', phoneCode: '886', name: 'Taiwan, Province Of China'}
    static TJ = {code: 'tj', phoneCode: '992', name: 'Tajikistan'}
    static TZ = {code: 'tz', phoneCode: '255', name: 'Tanzania, United Republic Of'}
    static TH = {code: 'th', phoneCode: '66', name: 'Thailand'}
    static TG = {code: 'tg', phoneCode: '228', name: 'Togo'}
    static TK = {code: 'tk', phoneCode: '690', name: 'Tokelau'}
    static TO = {code: 'to', phoneCode: '676', name: 'Tonga'}
    static TN = {code: 'tn', phoneCode: '216', name: 'Tunisia'}
    static TR = {code: 'tr', phoneCode: '90', name: 'Turkey'}
    static TM = {code: 'tm', phoneCode: '993', name: 'Turkmenistan'}
    static TV = {code: 'tv', phoneCode: '688', name: 'Tuvalu'}
    static AE = {code: 'ae', phoneCode: '971', name: 'United Arab Emirates'}
    static UG = {code: 'ug', phoneCode: '256', name: 'Uganda'}
    static GB = {code: 'gb', phoneCode: '44', name: 'United Kingdom'}
    static UA = {code: 'ua', phoneCode: '380', name: 'Ukraine'}
    static UY = {code: 'uy', phoneCode: '598', name: 'Uruguay'}
    static US = {code: 'us', phoneCode: '1', name: 'United States'}
    static UZ = {code: 'uz', phoneCode: '998', name: 'Uzbekistan'}
    static VU = {code: 'vu', phoneCode: '678', name: 'Vanuatu'}
    static VA = {code: 'va', phoneCode: '39', name: 'Holy See (vatican City State)'}
    static VE = {code: 've', phoneCode: '58', name: 'Venezuela, Bolivarian Republic Of'}
    static VN = {code: 'vn', phoneCode: '84', name: 'Viet Nam'}
    static WF = {code: 'wf', phoneCode: '681', name: 'Wallis And Futuna'}
    static YE = {code: 'ye', phoneCode: '967', name: 'Yemen'}
    static ZM = {code: 'zm', phoneCode: '260', name: 'Zambia'}
    static ZW = {code: 'zw', phoneCode: '263', name: 'Zimbabwe'}
}
export = CountryCode