enum ScheduledTaskType
{
    CALL = 1,
    CALL_SCHEDULE,
    EMAIL_MOBILE_VERIFICATION_REMINDER,
    CALL_REMINDER_NOTIFICATION,
    TIMEZONE_REFRESH,
    TEST_TIMESTAMP_PRINT,
    SAVE_STATS
}
export = ScheduledTaskType