enum UserSetting
{
    PASSWORD_RESET_TOKEN,
    PASSWORD_RESET_TOKEN_EXPIRY,
    EMAIL_VERIFICATION_TOKEN,
    EMAIL_VERIFICATION_TOKEN_EXPIRY,
    MOBILE_VERIFICATION_TOKEN,
    MOBILE_VERIFICATION_TOKEN_EXPIRY
}
export = UserSetting