import ModelDecorators = require("./decorators/ModelDecorators");
import CountryCode = require("./enums/CountryCode");
import CountryName = require("./enums/CountryName");
import DayName = require("./enums/DayName");
import ForeignKeyType = require("./enums/ForeignKeyType");
import ImageSize = require("./enums/ImageSize");
import Salutation = require("./enums/Salutation");
import AbstractModel = require("./models/AbstractModel");
import BaseModel = require("./models/BaseModel");
import BaseS3Model = require("./models/BaseS3Model");
import ForeignKey = require("./models/ForeignKey");
import SolrDao = require("./dao/SolrDao");
import MysqlDao = require("./dao/MysqlDao");
import BaseMappingDao = require("./dao/BaseMappingDao");
import BaseDaoDelegate = require("./delegates/BaseDaoDelegate");
import BaseApi = require("./api/BaseApi");
import FileWatcherDelegate = require("./delegates/FileWatcherDelegate");
import GlobalIDDelegate = require("./delegates/GlobalIDDelegate");
import ImageDelegate = require("./delegates/ImageDelegate");
import LocalizationDelegate = require("./delegates/LocalizationDelegate");
import MysqlDelegate = require("./delegates/MysqlDelegate");
import Formatter = require("./common/Formatter");
import Utils = require("./common/Utils");
import sqlToModel = require("./common/sqlToModel");
import CacheHelper = require("./caches/CacheHelper");
declare var exported: {
    CountryCode: typeof CountryCode;
    CountryName: typeof CountryName;
    DayName: typeof DayName;
    ForeignKeyType: typeof ForeignKeyType;
    ImageSize: typeof ImageSize;
    Salutation: typeof Salutation;
    AbstractModel: typeof AbstractModel;
    BaseModel: typeof BaseModel;
    BaseS3Model: typeof BaseS3Model;
    ForeignKey: typeof ForeignKey;
    SolrDao: typeof SolrDao;
    MysqlDao: typeof MysqlDao;
    BaseMappingDao: typeof BaseMappingDao;
    BaseDaoDelegate: typeof BaseDaoDelegate;
    BaseApi: typeof BaseApi;
    FileWatcherDelegate: typeof FileWatcherDelegate;
    GlobalIDDelegate: typeof GlobalIDDelegate;
    ImageDelegate: typeof ImageDelegate;
    LocalizationDelegate: typeof LocalizationDelegate;
    MysqlDelegate: typeof MysqlDelegate;
    Formatter: typeof Formatter;
    Utils: typeof Utils;
    sqlToModel: typeof sqlToModel;
    CacheHelper: typeof CacheHelper;
    ModelDecorators: typeof ModelDecorators;
};
export = exported;
